### ISSUE TITLE
JDK Binary handlers should be provided

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-microstream#21]
### Issue description

We currently do:

```
        foundation.onConnectionFoundation(BinaryHandlersJDK8::registerJDK8TypeHandlers);
```

To get type providers for the common JDK types bound.

There is a [different binder for JDK17](https://search.maven.org/artifact/one.microstream/microstream-persistence-binary-jdk17/06.01.00-MS-GA/jar), and we need to provide a way to use these in place of the Java 8 ones

**Comment by sdelamo** [comment]
If you use JDK 17? Should you register both JDK 8 and JDK 17?

**Comment by timyates** [comment]
I think yes..  looking at the [8](https://github.com/microstream-one/microstream/blob/f34a51efb714b2a9de4c1aadd2c0986d05e6341d/persistence/binary-jdk8/src/main/java/one/microstream/persistence/binary/jdk8/types/BinaryHandlersJDK8.java#L40) and [17](https://github.com/microstream-one/microstream/blob/f34a51efb714b2a9de4c1aadd2c0986d05e6341d/persistence/binary-jdk17/src/main/java/one/microstream/persistence/binary/jdk17/types/BinaryHandlersJDK17.java#L33) classes, it doesn't look like 17 does the earlier classes

There is also an [android](https://github.com/microstream-one/microstream/tree/f34a51efb714b2a9de4c1aadd2c0986d05e6341d/persistence) persistence helper, but.I guess we don't need to worry about that for now

**Comment by sdelamo** [comment]
> There is also an [android](https://github.com/microstream-one/microstream/tree/f34a51efb714b2a9de4c1aadd2c0986d05e6341d/persistence) persistence helper, but.I guess we don't need to worry about that for now

We can skip that now

**Comment by timyates** [comment]
I pushed in Java 8 handlers by default in https://github.com/micronaut-projects/micronaut-microstream/pull/97

You have to be on java 8 to run micronaut, so having the java 8 optimizations seems sensible

**Comment by sdelamo** [comment]
what about 17 handlers?

**Comment by timyates** [comment]
@sdelamo Can we bump the Java 17 handlers until Micronaut 4.0.0?  We will have to compile anything we do under Java 17, and it will be much simpler once we make the jump to Java 17 as a baseline?

**Comment by sdelamo** [comment]
`master` branch is already for next mayor. You can work on this and target that branch as base
