### ISSUE TITLE
Add a new module for exposing Microstream REST Interface

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-microstream#24]
### Feature description

Microstream provides a library for a low-level view of the storage

https://search.maven.org/search?q=a:microstream-storage-restservice-sparkjava

We should create a module that uses this dependency and creates an endpoint for each defined storage in the app

Configuration to enable/disable per storage, and alter the port used should be handled (with sensible defaults)

We should also provide documentation on how to download the client, and inspect your data

**Comment by sdelamo** [comment]
Sub tasks: 

- [ ] #32
- [ ] #33 
- [ ] #34
- [ ] #35

**Comment by timyates** [comment]
Closed via https://github.com/micronaut-projects/micronaut-microstream/pull/40
