### ISSUE TITLE
Create a Graal tests application

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-microstream#47]
### Issue description

We should have a repository in a our graal tests suite.  It will tests that micronaut microstream works with graalvm

We need to create a repository similar to 

https://github.com/micronaut-graal-tests/micronaut-basic-app

We will need to added to the tests scheduler but I can look into it once we have the app.

**Comment by sdelamo** [comment]
@timyates you should have an invitation to join the `micronatu-graal-tests` github organization.

**Comment by sdelamo** [comment]
I have created the repo. 

Please, create a PR against https://github.com/micronaut-graal-tests/micronaut-microstream/tree/3.4.x

**Comment by timyates** [comment]
This isn't how we do things anymore
