### ISSUE TITLE
Switch from Jackson to Serde

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-microstream#48]
Once this is fixed https://github.com/micronaut-projects/micronaut-serialization/issues/196 we can switch from Jackson to Serde for our serialization

**Comment by timyates** [comment]
Found a bug in Serde (different one) https://github.com/micronaut-projects/micronaut-serialization/issues/245

**Comment by sdelamo** [comment]
@timyates is it possible to move to serialization now?
